### ISSUE TITLE
Suspicious field in index pattern.

### ISSUE THREAD

**Issue by whataboutpereira** [enotspe/fortinet-2-elasticsearch#4]
Hello! I'm looking at an odd field in the index patterns for ecs-fortigate-* - `Technology\"cat`

I can only suspect it's erroneous. :)

**Comment by enotspe** [comment]
Hello! Yes, that was an error indeed.

**Comment by enotspe** [comment]
I found the root cause. (I really hope no one will have to dealt with it).

It turns out that logid=0100032546 causes a parser error. The `msg` on this log is way to long. It seems that issue is on logstash side, but we are still debugging. After a certain lenght, all the rest value of `msg` continues been evaluated as key/value, but it is actually part of the value of `msg`

This logid refers to an application crash message. It only is happening on one (out of 100s) firewal, so I guess I might be a bug. 

[Fortinet forum](https://forum.fortinet.com/tm.aspx?m=118706)

**Comment by enotspe** [comment]
we have updated drop pipeline, so ti can filter out these weird fields caused by logid=0100032546

**Comment by enotspe** [comment]
closed on #7
