### ISSUE TITLE
kibana index patterns

### ISSUE THREAD

**Issue by pzmq** [enotspe/fortinet-2-elasticsearch#7]
when i first imported the kibana index patterns they looked like this

![image](https://user-images.githubusercontent.com/1643249/78654685-d0c55700-78bc-11ea-887c-7a5bdf9cdd1f.png)

i think this might be some misconfiguration or on my behalf or on the files provided...

PS: this is regarding the `ecs-fortigate-*`

Can someone give me a hint of what could've worked wrong?

**Comment by enotspe** [comment]
Hi, I am afraid is no error from your side. As we explainend on #4 , there was an error when parsing logid=0100032546 because `msg` is to long for kv filter. We have an ongoing case with Fortinet regarding why we get those messages anyway. 

I don´t know how to erase those fields once they are on the index pattern, tough. If you find the way, please post it here.

**Comment by enotspe** [comment]
you should just refresh the index pattern in order to clear up those strange fields

![image](https://user-images.githubusercontent.com/47488630/89608766-a324f600-d83b-11ea-85b6-742bc6d287ff.png)
